name: Sync LeetCode

on:
  workflow_dispatch:
  schedule:
    - cron: "0 8 * * *"

jobs:
  sync:
    runs-on: ubuntu-latest

    steps:
      - name: Run LeetCode Synchronizer
        uses: dos-m0nk3y/LeetCode-Synchronizer@v1.1.0
        with:
          GITHUB_TOKEN: ${{ github.token }}
          LEETCODE_SESSION: ${{ secrets.LEETCODE_SESSION }}
          LEETCODE_CSRF_TOKEN: ${{ secrets.LEETCODE_CSRF_TOKEN }}
